### ISSUE TITLE
multipart upload is broken

### ISSUE THREAD

**Issue by TheZ3ro** [nikkiii/embedhttp#15]
Hello, is this project still in development?

I was trying to implement POST multipart request for file uploading on a simple web server and I've take the MultipartReader.java from embedhttp.

It works great with text file or small image file, but with image >1MB (almost) the Reader "delete" some bytes or change arbitrary position bytes ("0x50" become "0x7F" and so on corrupting my PNG file).

On text file > 1MB nothing strange happend.

What do you think? I don't think it's an Encoding error because doesn't change all the 0x50

**Comment by nikkiii** [comment]
I'm not sure, I don't really use this for any active projects, and even then I never really used Multipart. It could be something in the implementation, since it was my first time dealing with something like this (Boundaries and finding the end of the data as it goes) so it may be an issue with MultipartReader stopping early or even too late, or it could be some extra data getting by in the implementation.

I don't believe it'd be encoding like you said, because it's simply reading the raw data and writing it back out to the temporary buffer file.

**Comment by TheZ3ro** [comment]
Thanks for the reply.
I have read your implementation and seems good to me. The strange thing is that text files are good but other binary format file are corrupted.
I think I will try to implement my own multipart parser. Thanks.

**Comment by TheZ3ro** [comment]
Solved :D
